extends: existence
message: "Avoid generic calls to action: '%s'"
link: http://docs.iechor.com/contribute/style/formatting/#links
level: warning
scope: raw
ignorecase: true
raw:
  - \[(click here|(find out|learn) more)\]
