services:
  server:
    image: xingqiangchen/iechor-docs:build
    ports:
      - "1313:1313"
    entrypoint:
      ["hugo", "server", "--bind", "0.0.0.0", "--environment", "production"]
    volumes:
      - .:/src
    working_dir: /src

    develop:
      watch:
        - action: sync
          path: .
          target: /src
          ignore:
            - node_modules/
