blank_issues_enabled: false
contact_links:
  - Name: Slack
    url: https://dockr.ly/comm-slack
    about: Ask questions in the iEchor Community Slack
  - name: Moby
    url: https://github.com/moby/moby/issues
    about: Bug reports for iEchor Engine
  - name: iEchor Desktop for Windows
    url: https://github.com/iechor/for-win/issues
    about: Bug reports for iEchor Desktop for Windows 
  - name: iEchor Desktop for Mac
    url: https://github.com/iechor/for-mac/issues
    about: Bug reports for iEchor Desktop for Mac 
  - name: iEchor Desktop for Linux
    url: https://github.com/iechor/for-linux/issues
    about: Bug reports for iEchor Desktop for Linux 
  - name: iEchor Compose
    url: https://github.com/iechor/compose/issues
    about: Bug reports for iEchor Compose
  - name: iEchor Buildx
    url: https://github.com/iechor/buildx/issues
    about: Bug reports for iEchor Buildx
